services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voting-app-be
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - CORS_ORIGINS=http://localhost:3000
      - AWS_ACCESS_KEY_ID=AKIA4XN4ORLBAK6IRIN4
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=ap-east-1
