services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voting-app-be
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - CORS_ORIGINS=http://localhost:3000
      - AWS_ACCESS_KEY_ID=AAK
      - AWS_SECRET_ACCESS_KEY=ASA
      - AWS_DEFAULT_REGION=ADR
